modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="BarryAlen777"
logoFile="logo.png"
description='''把 1.12.2 的苹果树玩法带到 Forge 1.20.1'''
[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraft_version}]"
ordering="NONE"
side="BOTH"
